### ISSUE TITLE
almost just a vertical line

### ISSUE THREAD

**Issue by jjjaneee** [rbouckaert/DensiTree#10]
Hi,
there was just a vertical line and species id instead of the topology of the tree on the window after I loaded the tree file (.nex) with branch length into this program. Which parameters in the toolbar should I adjust to show the topology of the tree?

Thanks！

**Comment by rbouckaert** [comment]
@jjjaneee I have only seen this before when I loaded a tree set, then loaded another tree set. There seems to be some interaction between previously loaded files, but I am not sure why this is happening. Sometimes redrawing the tree set (menu Draw All/Draw Tree Set) or reloading the file will do the trick. If that does not work, can you make the tree file available so I can investigate?

**Comment by jjjaneee** [comment]
This  problem has been resoved,thanks a lot !
