### ISSUE TITLE
error loading file:null

### ISSUE THREAD

**Issue by essaylang** [rbouckaert/DensiTree#4]
Hi Remco,
I am using DensiTree to visualize  gene tree files output from MrBayes, but ~1/3 of the files do not load correctly;I get an error message that says, "error loading file:null".  The tree does appear, but as a tiny, condensed figure in the upper left of the screen and I can't do anything with it. I have compared the files that open with those that don't in a text editor, but can't find anything wrong. Any idea what the problem might be? For example, the COI tree is good; the Nad5 tree is bad.

[COI_tree.txt](https://github.com/rbouckaert/DensiTree/files/370377/COI_tree.txt)
[Nad5_tree.txt](https://github.com/rbouckaert/DensiTree/files/370376/Nad5_tree.txt)

Any advice is welcome, and thanks for a really great application!
Regards,
Shirley

**Comment by rbouckaert** [comment]
Hi Shirly,

Both files run fine with the latest development version. Perhaps you can try downloading

http://hudson.cs.auckland.ac.nz/job/DensiTree/lastSuccessfulBuild/artifact/dist/lib/DensiTree.jar

and see whether that works?
Cheers,
Remco

**Comment by essaylang** [comment]
Hi Remco,

Thanks! The newer version seems to accept all of my files. I appreciate your help.

Regards,

Shirley
